PINECONE_API_KEY: "pcsk_644J9s_2JrQF6KeET3uVmWheRPKbc1QaoKyPYSpFGqMZWEgVtA8yjDiVAKgC5F3K5TMKSL"
PINECONE_API_ENV: "us-east-1"
PINECONE_INDEX_NAME: "medicine"
GOOGLE_API_KEY: "AIzaSyBXkPsu1ji7wSfixufEskZI4i_ORcbFwsQ"